name: PR

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Formatting & Clippy
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Prepare ELF for clippy
        run: |
          mkdir -p target/elf-compilation/docker/riscv64im-succinct-zkvm-elf/release
          cp elf/sp1-helios-elf target/elf-compilation/docker/riscv64im-succinct-zkvm-elf/release/sp1-helios-program

      - name: Run cargo clippy
        run: cargo clippy --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1
          SP1_SKIP_PROGRAM_BUILD: "true"
